### ISSUE TITLE
Error Ravendb 4.2

### ISSUE THREAD

**Issue by MohMehrnia** [JudahGabriel/RavenDB.StructuredLog#3]
When I used ravendb 4.2.5 show error message when to write log:
possibly disconnected. InvalidQueryExceptions: Suggestion query must be executed against static index

**Comment by JudahGabriel** [comment]
Strange. I'll have a look at this soon.

**Comment by JudahGabriel** [comment]
@MohMehrnia did you find the cause? I'd be glad to fix this if it still really is an issue.

**Comment by MohMehrnia** [comment]
No can not fix it,
When your delay to resolve I guess you very busy, thanks if you can resolving

**Comment by JudahGabriel** [comment]
Yeah, it's been busy here at work. :-) I will update this today.

**Comment by JudahGabriel** [comment]
@MohMehrnia I looked into this -- and the suggestions index gets created automatically, testing against live-sample.ravendb.net. I tried it using the Sample project in the repo.

How can I repro this problem?

**Comment by JudahGabriel** [comment]
I've uploaded a new version of this library, RavenDB.StructuredLogger v5.1, that gracefully handles fuzzy search failures like the one you describe.

Give it a spin and let me know if it's working for you.
